### ISSUE TITLE
Count element command handle the exception while element not exist but error appeared in the log

### ISSUE THREAD

**Issue by asho30** [MohabMohie/SHAFT_ENGINE#164]
**Describe the bug**

**To Reproduce**
1. Run script with command "	if(ElementActions.getElementsCount(driver, continueSaving_button) !=0){"
2. If element not exist exception handled but appeared in the log

**Expected behavior**
Count element command handle the exception while element not exist.

**Screenshots**
![eclipse-workspace - hemma-testing_src_test_resourc](https://user-images.githubusercontent.com/28779919/87245791-a13c6280-c448-11ea-9e2d-8a19fe65c4a9.png)

[allure-results 1.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4908451/allure-results.1.zip)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 83

**Comment by MohabMohie** [comment]
after investigating this case, it seems that this is only a discrete log message not an actual exception being thrown.
![image](https://user-images.githubusercontent.com/19201898/87881637-dc1b3900-c9fa-11ea-8fec-6cf4aacf827e.png)

this can be disabled by changing this parameter to off instead of info
