### ISSUE TITLE
Support for validating Graphql API Response (without repetitive steps).

### ISSUE THREAD

**Issue by hammad101088** [MohabMohie/SHAFT_ENGINE#312]
- There were some repetitive steps while validating graphql response, so I had to build a custom method for validating the response (works with any graphql response)
- by validating I mean comparing an expected value with an actual value from the response

I'd like to suggest that:
- assertion method for asserting any graphql response 
- verification method for verifying any graphql response

**Comment by MohabMohie** [comment]
I saw your sample project and I believe that they can be generic methods since they accept the response object, jsonpath, and expected object.

So maybe we can create two assertions that can be used for all API actions and add them to the validations library (verify and assert).

Since you already implemented the code in your sample project, would you like to create a PR and merge it with the engine?

**Comment by hammad101088** [comment]
I'd be happy to do so, kindly wait for the PR. @MohabMohie
