### ISSUE TITLE
support for Headless mode with MsEdge

### ISSUE THREAD

**Issue by sa94my** [MohabMohie/SHAFT_ENGINE#338]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, rather a suggestion to make use of a new feature.

**Description**
- Upon trying to generate configuration file from the configuration manager I could not select the headless mode with Edge 
browser 
- I got the error message "This only works for Chrome and Firefox" 
- Then I moved to the code base (DriverFactoryHelper ) to check if this is a configuration manager issue , and found out there is no support for Microsoft Edge headless mode 

**Describe the solution you'd like**
To my naive understanding , we can add a check for the feature value and then set it (basically the same as in chrome driver case)

**Comment by MohabMohie** [comment]
Kindly note that this is not natively supported by Selenium 3.x because it's older than Edge (Chromium).
![image](https://user-images.githubusercontent.com/19201898/121776567-ea7fbf80-cb8d-11eb-9d3a-d9fa4609bf72.png)
Source: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=java

It will be natively supported by Selenium 4 which SHAFT will be upgraded to once Appium is also upgraded, so if there is no urgent need I would recommend using headless testing on Chrome for now since they're both Chromium Based.

**Comment by sa94my** [comment]
Thank you for the informative reply .
there is no urgent need, I was just exploring and saw room for improvement (or at least thought so).

**Comment by MohabMohie** [comment]
@sa94my thanks for opening this ticket, and please reopen it after shaft migrates to selenium 4. I'm sure it will be a valuable addition then.
