### ISSUE TITLE
When a page takes more time [delay] to upload some element  to click on it,   the result appears that the element is not attached to the page 

### ISSUE THREAD

**Issue by AalaaMustafa** [MohabMohie/SHAFT_ENGINE#450]
**Describe the bug**
I have a page that requires uploading three attachments with three buttons when the first attachment uploads and the page refreshes it takes time [Delay ] to appear the last two buttons. the issue appears here it returns that the element not attached to the page 
when I use [is element isdisplayed] this issue does not appear

**Screenshots**
![2021-11-08_15h12_15](https://user-images.githubusercontent.com/58508598/141768124-7528449e-7268-4869-997a-3219c73dbb19.png)
![2021-11-08_15h13_23](https://user-images.githubusercontent.com/58508598/141768164-b677a82b-cf7c-4fbe-8e56-2facbec4578c.png)
![2021-11-08_15h13_44](https://user-images.githubusercontent.com/58508598/141768183-881e418d-4f56-4115-a697-d6012e886281.png)
![2021-11-08_15h13_53](https://user-images.githubusercontent.com/58508598/141768210-6f905c2e-b8b2-4eb2-9ac6-998437aedf8b.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [ Chrome ]
 - Version [95]
 -  SHAFT-ENGINE [5.3.20210621]
 

**Additional context**
Thanks for your support. 
I’d really appreciate your help if it is solved in the shortest time.

**Comment by MohabMohie** [comment]
After investigating the above issue, here is the root cause:
- Element identification timeout is not sufficient and should be increased using the configuration manager.

There is also an issue from the Engine's side
- Exception should be handled not thrown as an error but a failure

Kindly try increasing the element identification timeout using the configuration manager and tell me if that solves your issue. Also, it is highly recommended to upgrade to the latest Beta engine version as it is using Selenium 4.0 and has much better performance and consistency overall.

I will keep the issue open, pending your confirmation that changing the timeouts resolved it.

**Comment by MohabMohie** [comment]
this issue will not happen with the latest engine release (coming soon) because clicking using javascript has been completely disabled. instead it will report failing to find the element which requires increasing the element identification timeout and/or number of attempts.
